export enum COMMON_CODE {
    PARAMS_ERROR = -1,
    TOKEN_IS_INVALID = -2,
    TOKEN_IS_EXPIRED = -3,
    ADDRESS_IS_EXIST = -4,
    CRYPTO_KEY_ERROR = -5,
    HTTP_REQ_ERROR = -6,
    TX_NOT_FOUND_ERROR = -7,
    RECORD_NOT_FOUND_ERROR = -8,
    SEND_EMAIL_ERROR = -9,
    CODE_NOT_MATCH_ERROR = -10,
    ADMIN_PASSWORD_ERROR = -11,
    DB_ERROR = -12,
    TOKEN_AMOUNT_NOT_ENOUGH_ERROR = -13,
    SOL_AMOUNT_NOT_ENOUGH_ERROR = -14,
    REDIS_ERROR = -15,
    SEND_EMAIL_EXCEED_LIMIT_ERROR = -16,
    EMAIL_BAN_ERROR = -17,
    COIN_IS_INVALID = -18,
    CEX_SNIPER_EXIST = -19,
    CEX_SNIPER_QUOTA_NOT_ENOUGH = -20,
    CEX_SNIPER_PEOPLE_NUMBER_EXCEED = -21,
    CEX_SNIPER_AMOUNT_TOO_SMALLER = -22,
    CEX_SNIPER_AMOUNT_TOO_HIGHER = -23,
    TOKEN_NOT_FOUND_ERROR = -24,
    PACKAGE_SOL_TRANSFER_ERROR = -25,
    MEME_REPORT_NOT_FOUND_ERROR = -26,
    EVAN_CLAIMING_ERROR = -27,
    USER_HAS_CLAIMED_ERROR = -28,
    CLAIM_END_ERROR = -29,
    USER_NO_TOKEN_TO_CLAIM = -30,
    TRANSFER_TOKEN_ERROR = -31,
    USER_SIGNATURE_VERIFY_ERROR = -32,
    USER_SIGNATURE_MESSAGE_NOT_MATCH_ERROR = -33,
    NO_PERMISSION_ERROR = -34,
    USER_ALREADY_EXIST_ERROR = -35,
    NOT_FOUND_USER_ERROR = -36,
    SYSTEM_ERROR = -9999,
}


export const COMMON_ERROR_MSG = {
    [COMMON_CODE.PARAMS_ERROR]: "param error",
    [COMMON_CODE.TOKEN_IS_INVALID]: "jwt token is invalid",
    [COMMON_CODE.TOKEN_IS_EXPIRED]: "jwt token is expired",
    [COMMON_CODE.ADDRESS_IS_EXIST]: "address is exist",
    [COMMON_CODE.CRYPTO_KEY_ERROR]: "crypto key error",
    [COMMON_CODE.HTTP_REQ_ERROR]: "internal service error",
    [COMMON_CODE.TX_NOT_FOUND_ERROR]: "transaction record not found error",
    [COMMON_CODE.RECORD_NOT_FOUND_ERROR]: "record not found error",
    [COMMON_CODE.SEND_EMAIL_ERROR]: "send email error",
    [COMMON_CODE.CODE_NOT_MATCH_ERROR]: "code not match",
    [COMMON_CODE.ADMIN_PASSWORD_ERROR]: "admin password error",
    [COMMON_CODE.DB_ERROR]: "db error",
    [COMMON_CODE.TOKEN_AMOUNT_NOT_ENOUGH_ERROR]: "token amount not enough error",
    [COMMON_CODE.SOL_AMOUNT_NOT_ENOUGH_ERROR]: "sol amount not enough error",
    [COMMON_CODE.REDIS_ERROR]: "redis error",
    [COMMON_CODE.SEND_EMAIL_EXCEED_LIMIT_ERROR]: "send email exceed limit error",
    [COMMON_CODE.EMAIL_BAN_ERROR]: "email login ban for 24 hours error",
    [COMMON_CODE.COIN_IS_INVALID]: "token is invalid",
    [COMMON_CODE.CEX_SNIPER_EXIST]: "cex sniper exist",
    [COMMON_CODE.CEX_SNIPER_QUOTA_NOT_ENOUGH]: "cex sniper quota not enough",
    [COMMON_CODE.CEX_SNIPER_PEOPLE_NUMBER_EXCEED]: "cex sniper people number exceed",
    [COMMON_CODE.CEX_SNIPER_AMOUNT_TOO_SMALLER]: "cex sniper amount too smaller",
    [COMMON_CODE.CEX_SNIPER_AMOUNT_TOO_HIGHER]: "cex sniper amount too higher",
    [COMMON_CODE.TOKEN_NOT_FOUND_ERROR]: "token not found error",
    [COMMON_CODE.PACKAGE_SOL_TRANSFER_ERROR]: "transfer sol for package error",
    [COMMON_CODE.MEME_REPORT_NOT_FOUND_ERROR]: "meme report not found for user address error",
    [COMMON_CODE.EVAN_CLAIMING_ERROR]: "evan claiming, please try later",
    [COMMON_CODE.USER_HAS_CLAIMED_ERROR]: "user has claimed",
    [COMMON_CODE.CLAIM_END_ERROR]: "claim end",
    [COMMON_CODE.USER_NO_TOKEN_TO_CLAIM]: "user has no token to claim",
    [COMMON_CODE.TRANSFER_TOKEN_ERROR]: "transfer token error",
    [COMMON_CODE.USER_SIGNATURE_VERIFY_ERROR]: "user signature verify error",
    [COMMON_CODE.USER_SIGNATURE_MESSAGE_NOT_MATCH_ERROR]: "user signature message not match error",
    [COMMON_CODE.NO_PERMISSION_ERROR]: "no permission",
    [COMMON_CODE.USER_ALREADY_EXIST_ERROR]: "user already exist",
    [COMMON_CODE.NOT_FOUND_USER_ERROR]: "user not found",
    [COMMON_CODE.SYSTEM_ERROR]: "system error",
}
